# Event Menue Order System (EMOS) Konfiguration
# Diese Datei wird von der Installation automatisch erstellt

database:
  host: "localhost"
  db_name: "menuselection"
  user: "root"
  pass: ""
  prefix: "menu_"

mail:
  admin_email: "admin@example.com"
  sender_name: "Event Menue Order System (EMOS)"

system:
  language: "de"
  timezone: "Europe/Berlin"
